config/routes.rb
StackOverflow::Application.routes.draw do

  resources :users
  resources :questions
  resources :responses
  resources :sessions
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, :presence => true
  validates :question, :presence => true

  belongs_to :user
  has_many :votes
  has_many :responses

end

app/models/response.rb
class Response < ActiveRecord::Base
  validates :response, :presence => true

  has_many :users, through: :votes
  has_many :votes
  belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :presence => true
  validates :password, :presence => true
  has_secure_password

  has_many :questions
  has_many :responses, through: :votes
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :response
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 private
  def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to "/questions", alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_filter :authorize, only: [:create]

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.create(question_params)
    if @question.save
      redirect_to("/questions")
    else
      flash[:alert] = "Invalid entries, please try again"
      render("new")
    end
  end

  def edit

  end

  def show
    @question = Question.find(params[:id])
    @response = Response.new
  end


private
  def question_params
    params.require(:question).permit(:title, :question)
  end

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  def index
  end

  def create
    @question = Question.find_by(params[:id])
    @response = @question.responses.new(response_params)
    if @response.save
      redirect_to("/questions")
    else
      render("/questions/show")
    end
  end

  def edit
  end

  def show
  end

  def update
  end
private
  def response_params
    params.require(:response).permit(:response)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.find_by_name(params[:name])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to("/questions")
      flash[:notice] = "User succesfully logged in"
    else
      flash[:notice] = "Invalid log in"
      render("new")
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to("/questions")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.new
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User succesfully created"
      redirect_to("/questions")
    else
      alert[:notice] = "Invalid entries, try again please"
      render("index.html.erb")
    end
  end

  def edit
  end

  def show
  end

private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackOverflow</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div id="user_header">
    <%= link_to "Home", questions_path %>  |

    <% if current_user %>
      Logged in as <%= current_user.name %> ...
      <%= link_to "Log Out", session_path("current"), method: "delete" %> |

      <% else %>
        <%= link_to "Log in", new_session_path %>  |
        <%= link_to "Sign Up", users_path %>  |
        <% end %>
  </div>
  <%= bootstrap_flash %>

  <%= yield %>
</div>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <% if @question.errors.any? %>
    <div class="error_messages">
      <h2 class="error">Form is invaid</h2>
      <ul>
        <% @question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %></br>
    <%=f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :question %></br>
    <%=f.text_area :question, size: "25x10" %>
  </div>

  <%= f.submit("Submit", :class => "btn btn-default") %>
  <% end %>

app/views/questions/index.html.erb
<h1 class="green">Stack Overflow</h1>


<%= link_to "New Topic", new_question_path, :class => "btn btn-default" %>
<h3>Topics:</h3>

<ul>
  <% @questions.each do |question| %>
    <li><%= link_to question.title, question_path(question.id) %></li>
  <% end %>
</ul>

app/views/questions/new.html.erb
<h1>Create a new topic</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<h2><%= @question.title %></h2>


<p class="thread"><%= @question.question %></p>

<%= render './responses/form' %>

app/views/responses/_form.html.erb
<%= form_for @response do |f| %>
<% if @response.errors.any? %>
  <div class="error_messages">
    <h2 class="error">Form is invaid</h2>
    <ul>
      <% @response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.label :response %></br>
  <%=f.text_area :response, size: "20x10"%>
</div>
<%= f.submit("Post Reply", :class => "btn btn-default") %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2 class="error">Form is invaid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %></br>
    <%=f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :password %></br>
    <%=f.password_field :password %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %></br>
    <%=f.password_field :password_confirmation %>
  </div>
  <%= f.submit("Sign up", :class => "btn btn-default") %>
  <% end %>

app/views/users/index.html.erb
<h1>Log in or sign up</h1>


<%= render 'form' %>


<ul>
  <% @users.each do |user| %>
    <li><%= user.name %></li>
  <% end %>
</ul>